exclude: '^ex_app/(img|js)/|.*\.phar'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        files: ex_app/lib/

-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
        files: ex_app/lib/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
    -   id: ruff
