name: Publish CUDA Image

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build image
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'nextcloud' }}  # REPLACE THIS WITH YOUR ORGANIZATION NAME
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Extract version from XML
        id: extract_version
        run: |
          VERSION=$(xmlstarlet sel -t -v "//image-tag" appinfo/info.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log version
        run: |
          echo "Extracted version: ${{ env.VERSION }}"

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          no-cache: true
          push: true
          context: .
          platforms: linux/amd64
          file: Dockerfile
          tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }}-cuda
          build-args: |
            BUILD_TYPE=cuda
